/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAskRouteImport } from './routes/_app/ask'
import { Route as AppConnectionsRouteImport } from './routes/_app/connections'
import { Route as AppSchemaRouteImport } from './routes/_app/schema'
import { Route as AppSqlRouteImport } from './routes/_app/sql'
import { Route as AppTablesRouteImport } from './routes/_app/tables'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAskRoute = AppAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectionsRoute = AppConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => AppRoute,
} as any)
const AppSchemaRoute = AppSchemaRouteImport.update({
  id: '/schema',
  path: '/schema',
  getParentRoute: () => AppRoute,
} as any)
const AppSqlRoute = AppSqlRouteImport.update({
  id: '/sql',
  path: '/sql',
  getParentRoute: () => AppRoute,
} as any)
const AppTablesRoute = AppTablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/ask': typeof AppAskRoute
  '/connections': typeof AppConnectionsRoute
  '/schema': typeof AppSchemaRoute
  '/sql': typeof AppSqlRoute
  '/tables': typeof AppTablesRoute
}
export interface FileRoutesByTo {
  '/ask': typeof AppAskRoute
  '/connections': typeof AppConnectionsRoute
  '/schema': typeof AppSchemaRoute
  '/sql': typeof AppSqlRoute
  '/tables': typeof AppTablesRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/ask': typeof AppAskRoute
  '/_app/connections': typeof AppConnectionsRoute
  '/_app/schema': typeof AppSchemaRoute
  '/_app/sql': typeof AppSqlRoute
  '/_app/tables': typeof AppTablesRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ask' | '/connections' | '/schema' | '/sql' | '/tables'
  fileRoutesByTo: FileRoutesByTo
  to: '/ask' | '/connections' | '/schema' | '/sql' | '/tables' | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/ask'
    | '/_app/connections'
    | '/_app/schema'
    | '/_app/sql'
    | '/_app/tables'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ask': {
      id: '/_app/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AppAskRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connections': {
      id: '/_app/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof AppConnectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/schema': {
      id: '/_app/schema'
      path: '/schema'
      fullPath: '/schema'
      preLoaderRoute: typeof AppSchemaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sql': {
      id: '/_app/sql'
      path: '/sql'
      fullPath: '/sql'
      preLoaderRoute: typeof AppSqlRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tables': {
      id: '/_app/tables'
      path: '/tables'
      fullPath: '/tables'
      preLoaderRoute: typeof AppTablesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAskRoute: typeof AppAskRoute
  AppConnectionsRoute: typeof AppConnectionsRoute
  AppSchemaRoute: typeof AppSchemaRoute
  AppSqlRoute: typeof AppSqlRoute
  AppTablesRoute: typeof AppTablesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAskRoute: AppAskRoute,
  AppConnectionsRoute: AppConnectionsRoute,
  AppSchemaRoute: AppSchemaRoute,
  AppSqlRoute: AppSqlRoute,
  AppTablesRoute: AppTablesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
